services:
  app:
    build: app/
    image: user-new:latest
    env_file:
      - app/.env
    volumes:
      - ./app:/app
  web-proxy:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  rabbitmq:
    image: rabbitmq:4.1-rc-alpine
    restart: on-failure
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmg_volume:/var/lib/rabbitmq
  database:
    image: postgres:17-alpine
    volumes:
      - postgres_volume:/var/lib/postgres
volumes:
  rabbitmg_volume:
  postgres_volume: