version: "3"
services:
  app:
    build: ./app/.env
    image: user-new:latest
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    web:
      build: ./nginx
      ports:
        - 80:80
        - 443:443
      depends_on:
        - app